import mongoose from 'mongoose';
import { createSchema } from './baseSchema.js';

const sellRequestSchema = createSchema({
  user_id: { type: String, default: null },
  customer_name: { type: String, default: null },
  customer_phone: { type: String, default: null },
  customer_email: { type: String, default: null },
  brand: { type: String, required: true },
  model: { type: String, required: true },
  device_title: { type: String, default: null },
  device_image: { type: String, default: null },
  ram: { type: String, default: null },
  storage: { type: String, default: null },
  condition: { type: String, default: 'Good' },
  screen_condition: { type: String, default: null },
  body_condition: { type: String, default: null },
  can_make_calls: { type: Boolean, default: true },
  under_warranty: { type: Boolean, default: false },
  defects: { type: [String], default: [] },
  imei: { type: String, default: null },
  imei_photo: { type: String, default: null },
  device_photos: {
    front: { type: String, default: null },
    back: { type: String, default: null },
    edges: { type: String, default: null },
    bill_box: { type: String, default: null },
  },
  diagnostics: {
    screen_touch: { type: Boolean, default: true },
    cameras: { type: Boolean, default: true },
    battery_health: { type: String, default: null },
    biometrics: { type: Boolean, default: true },
    speaker_mic: { type: Boolean, default: true },
    charging_port: { type: Boolean, default: true },
  },
  accessories: { type: [String], default: [] },
  estimated_price: { type: Number, default: null },
  valuation_price: { type: Number, default: null },
  final_price: { type: Number, default: null },
  status: {
    type: String,
    default: 'pending',
  },
  pickup_address: { type: String, default: null },
  pickup_area: { type: String, default: null },
  pickup_date: { type: String, default: null },
  pickup_slot: { type: String, default: null },
  notes: { type: String, default: null },
  assigned_agent_id: { type: String, default: null },
  pickup_person_name: { type: String, default: null },
  pickup_person_phone: { type: String, default: null },
  estimated_arrival_time: { type: String, default: null },
  payout_method: { type: String, default: 'UPI / Spot Cash' },
  payout_details: { type: String, default: null },
  assigned_vendor_id: { type: String, default: null },
  forwarded_to_vendor: { type: Boolean, default: false },
  vendor_quote_price: { type: Number, default: null },
  vendor_notes: { type: String, default: null },
  vendor_quote_status: { type: String, default: 'none' }, // 'none', 'pending_inspection', 'quoted', 'user_accepted', 'user_rejected', 'completed'
  commission_percent: { type: Number, default: 10 },
  commission_amount: { type: Number, default: null },
  paid_via_vendor_limit: { type: Boolean, default: false },
}, { timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } });

export const SellRequest = mongoose.models.SellRequest || mongoose.model('SellRequest', sellRequestSchema);
